-- Demo data for the help screenshots job and the deals/voice/help e2e spec (section 12c:
-- "demo data only, never her real content"). Every row id starts with demo_ or uses version 9001
-- so tests/e2e/demo.ts can remove it again; brands/pitches/deals/narrations are reset whole
-- because only these specs create them. Idempotent: it clears before it inserts.

DELETE FROM posts WHERE id LIKE 'demo_%';
DELETE FROM narrations;
DELETE FROM deal_emails;
DELETE FROM deal_offers;
DELETE FROM pitches;
DELETE FROM deals;
DELETE FROM media_kit_versions;
DELETE FROM kit_views;
DELETE FROM kit_slugs WHERE slug != 'sheila';
DELETE FROM settings WHERE key = 'marketplaces_joined';
DELETE FROM brand_contacts;
DELETE FROM brands;
DELETE FROM account_stats WHERE id LIKE 'demo_%';
DELETE FROM clips WHERE id LIKE 'demo_%';
DELETE FROM assets WHERE id LIKE 'demo_%';
DELETE FROM dumps WHERE id LIKE 'demo_%';
DELETE FROM brand_profile WHERE version = 9001;
DELETE FROM research_briefs WHERE version = 9001;
UPDATE media_kit SET bio = '', photo_r2_key = NULL, featured_clip_ids = '[]', past_partners = '[]', rates = NULL, public_slug = 'sheila', contact_email = NULL, updated_at = NULL, draft = NULL, draft_saved_at = NULL WHERE id = 1;
UPDATE voice SET sample_r2_key = NULL, consent_at = NULL, consent_text = NULL, model_r2_key = NULL, elevenlabs_voice_id = NULL, enabled = 0, updated_at = NULL WHERE id = 1;

INSERT INTO brand_profile (version, sections, locked, locked_at, source) VALUES (9001, '{"who": "Demo creator: a hostess and lifestyle creator who makes everyday gatherings feel special.", "audience": "Women 30-55 in the US who love hosting, table styling and easy entertaining.", "goals": "90 days: post 10 clips a week and land 2 paid partnerships. 1 year: a steady brand-deal income.", "voice": "Warm, gracious, a little playful; short sentences; never salesy.", "themes": "Table styling\nEasy entertaining\nHoliday hosting\nEveryday luxury", "do_dont": "Do: show real homes and real food. Don''t: fake reviews or hard selling.", "off_limits": "Alcohol, gambling, diet pills", "deal_fit": "Home, tableware, candles, florals, kitchen and gifting brands.", "ctas": "Follow for more hosting ideas; save this for your next gathering."}', 1, '2026-09-20T12:00:00.000Z', 'edited');
INSERT INTO research_briefs (version, body, sources, status, approved_at) VALUES (9001, '{"audience": [{"text": "Most engaged viewers are women 30-55.", "source_ids": ["s1"], "basis": "her_data", "confidence": "solid"}], "themes": [{"title": "Table styling", "claims": [{"text": "Tablescape videos get the most saves.", "source_ids": ["s1"], "basis": "web", "confidence": "solid"}]}], "hooks": [{"text": "Open on the finished table, then rewind.", "source_ids": ["s1"], "basis": "web", "confidence": "solid"}], "cut_styles": [{"text": "Hook-first cuts under 30 seconds hold best.", "source_ids": ["s1"], "basis": "web", "confidence": "solid"}], "best_times": {"tiktok": [], "instagram": [], "youtube": []}, "comparable_creators": [{"handle": "@demo.hostess", "platform": "tiktok", "why": {"text": "Same niche, similar size.", "source_ids": ["s1"], "basis": "web", "confidence": "solid"}}, {"handle": "@demo.tablescapes", "platform": "instagram", "why": {"text": "Runs paid partnerships with home brands.", "source_ids": ["s1"], "basis": "web", "confidence": "solid"}}], "shot_list": [{"text": "A 20-second table reset before guests arrive.", "source_ids": ["s1"], "basis": "web", "confidence": "solid"}]}', '[{"id": "s1", "url": "https://example.org/demo-source", "title": "Demo source", "kind": "web"}]', 'approved', '2026-09-21T12:00:00.000Z');
INSERT INTO dumps (id, door, notes, status, clips_made, created_at, ready_at) VALUES ('demo_dump', 'new', 'Demo footage: Sunday brunch table', 'reviewed', 8, '2026-09-22T15:00:00.000Z', '2026-09-22T16:00:00.000Z');
INSERT INTO assets (id, dump_id, file_name, mime_type, size_bytes, r2_key, upload_status) VALUES ('demo_ast', 'demo_dump', 'demo-brunch.mp4', 'video/mp4', 1000000, 'raw/demo_dump/demo_ast', 'uploaded');
INSERT INTO clips (id, asset_id, dump_id, start_s, end_s, recipe, hook_text, caption, hashtags, score, r2_key, media_token, status, reviewed_at) VALUES ('demo_clip_1', 'demo_ast', 'demo_dump', 0, 28, 'hook_first', 'Set a brunch table in 60 seconds', 'Demo caption for: Set a brunch table in 60 seconds', '#hosting #tablescape', 0.95, 'clips/demo_clip_1.mp4', 'demotoken0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'approved', '2026-09-22T17:00:00.000Z');
INSERT INTO clips (id, asset_id, dump_id, start_s, end_s, recipe, hook_text, caption, hashtags, score, r2_key, media_token, status, reviewed_at) VALUES ('demo_clip_2', 'demo_ast', 'demo_dump', 30, 58, 'hook_first', 'The one napkin fold everyone asks about', 'Demo caption for: The one napkin fold everyone asks about', '#hosting #tablescape', 0.91, 'clips/demo_clip_2.mp4', 'demotoken1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'approved', '2026-09-22T17:00:00.000Z');
INSERT INTO clips (id, asset_id, dump_id, start_s, end_s, recipe, hook_text, caption, hashtags, score, r2_key, media_token, status, reviewed_at) VALUES ('demo_clip_3', 'demo_ast', 'demo_dump', 60, 88, 'hook_first', 'Candles, but make it Sunday', 'Demo caption for: Candles, but make it Sunday', '#hosting #tablescape', 0.87, 'clips/demo_clip_3.mp4', 'demotoken2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'approved', '2026-09-22T17:00:00.000Z');
INSERT INTO clips (id, asset_id, dump_id, start_s, end_s, recipe, hook_text, caption, hashtags, score, r2_key, media_token, status, reviewed_at) VALUES ('demo_clip_4', 'demo_ast', 'demo_dump', 90, 118, 'hook_first', 'Holiday table on a budget', 'Demo caption for: Holiday table on a budget', '#hosting #tablescape', 0.83, 'clips/demo_clip_4.mp4', 'demotoken3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'approved', '2026-09-22T17:00:00.000Z');
INSERT INTO clips (id, asset_id, dump_id, start_s, end_s, recipe, hook_text, caption, hashtags, score, r2_key, media_token, status, reviewed_at) VALUES ('demo_clip_5', 'demo_ast', 'demo_dump', 120, 148, 'hook_first', 'Three-ingredient party board', 'Demo caption for: Three-ingredient party board', '#hosting #tablescape', 0.79, 'clips/demo_clip_5.mp4', 'demotoken4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'approved', '2026-09-22T17:00:00.000Z');
INSERT INTO clips (id, asset_id, dump_id, start_s, end_s, recipe, hook_text, caption, hashtags, score, r2_key, media_token, status, reviewed_at) VALUES ('demo_clip_6', 'demo_ast', 'demo_dump', 150, 178, 'hook_first', 'How I reset after guests leave', 'Demo caption for: How I reset after guests leave', '#hosting #tablescape', 0.75, 'clips/demo_clip_6.mp4', 'demotoken5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'approved', '2026-09-22T17:00:00.000Z');
INSERT INTO clips (id, asset_id, dump_id, start_s, end_s, recipe, hook_text, caption, hashtags, score, r2_key, media_token, status, reviewed_at) VALUES ('demo_clip_7', 'demo_ast', 'demo_dump', 180, 208, 'hook_first', 'The easiest centerpiece ever', 'Demo caption for: The easiest centerpiece ever', '#hosting #tablescape', 0.71, 'clips/demo_clip_7.mp4', 'demotoken6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'approved', '2026-09-22T17:00:00.000Z');
INSERT INTO clips (id, asset_id, dump_id, start_s, end_s, recipe, hook_text, caption, hashtags, score, r2_key, media_token, status, reviewed_at) VALUES ('demo_clip_8', 'demo_ast', 'demo_dump', 210, 238, 'hook_first', 'My go-to hosting playlist trick', 'Demo caption for: My go-to hosting playlist trick', '#hosting #tablescape', 0.67, 'clips/demo_clip_8.mp4', 'demotoken7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'approved', '2026-09-22T17:00:00.000Z');
INSERT INTO account_stats (id, platform, captured_at, followers, avg_views, source) VALUES ('demo_stats_tiktok', 'tiktok', '2026-09-24T12:00:00.000Z', 12400, 3100, 'api');
INSERT INTO account_stats (id, platform, captured_at, followers, avg_views, source) VALUES ('demo_stats_instagram', 'instagram', '2026-09-24T12:00:00.000Z', 8200, 1900, 'api');
INSERT INTO account_stats (id, platform, captured_at, followers, avg_views, source) VALUES ('demo_stats_youtube', 'youtube', '2026-09-24T12:00:00.000Z', 2100, 900, 'api');
UPDATE media_kit SET bio = 'Hosting, table styling and everyday luxury for women who love to gather.', featured_clip_ids = '["demo_clip_1","demo_clip_2","demo_clip_3"]', past_partners = '["Demo Candle Co.","Demo Linens"]', contact_email = 'partnerships@demo-creator.example', updated_at = '2026-09-24T12:00:00.000Z' WHERE id = 1;
UPDATE media_kit SET draft = '{"name": "Sheila Bruce", "handles": {"tiktok": "@demo.sheila", "instagram": "@demo.sheila"}, "niche": "Hosting \u00b7 tablescapes \u00b7 everyday luxury", "location": "Mobile, Alabama", "positioning": "Hosting that makes every guest feel celebrated.", "bio": "Hosting, table styling and everyday luxury for women who love to gather.", "photoKey": null, "pillars": [{"title": "Table styling", "text": "Tablescapes for every season"}, {"title": "Easy entertaining", "text": "Gatherings without the stress"}, {"title": "Holiday hosting", "text": "Menus, tables and gifts"}], "series": [{"title": "Sunday Table", "text": "A weekly 60-second table reset"}], "showcase": ["demo_clip_1", "demo_clip_2", "demo_clip_3"], "collabs": [{"id": "col_1", "brand": "Demo Candle Co.", "website": null, "logoKey": null, "what": "2 TikToks for a holiday launch", "result": "48K views, 1.2K saves", "dealId": null}, {"id": "col_2", "brand": "Demo Linens", "website": null, "logoKey": null, "what": "Instagram Reel + Stories", "result": "", "dealId": null}], "packages": [{"id": "pkg_tiktok", "name": "1 TikTok video", "items": [{"key": "tiktok_video", "qty": 1}], "startingAt": 800, "onRequest": false, "floor": 650, "target": 1000, "note": "Concept, filming and editing; posted on my TikTok.", "showOnKit": true}, {"id": "pkg_reel_story", "name": "Instagram Reel + Story set", "items": [{"key": "ig_reel", "qty": 1}, {"key": "ig_story_set", "qty": 1}], "startingAt": null, "onRequest": true, "floor": null, "target": null, "note": "A Reel plus three Story frames with your link.", "showOnKit": true}, {"id": "pkg_bundle", "name": "3-video bundle", "items": [{"key": "tiktok_video", "qty": 2}, {"key": "ig_reel", "qty": 1}], "startingAt": 2100, "onRequest": false, "floor": 1800, "target": 2400, "note": "Three videos across TikTok and Instagram over a month.", "showOnKit": true}, {"id": "pkg_ugc", "name": "Video for your channels (no post)", "items": [{"key": "ugc_video", "qty": 1}], "startingAt": 350, "onRequest": false, "floor": 250, "target": 450, "note": "A finished video for you to post.", "showOnKit": true}], "addons": {"usagePctPer30d": 30, "paidUsagePctPer30d": 40, "exclusivityPctPerMonth": 25, "rushPct": null, "bundleDiscountPct": 10, "killFeePct": 50, "upfrontPct": 50, "upfrontOver": 1000, "netDays": 30, "revisionRounds": 2}, "testimonials": [{"quote": "Sheila''s table sold out our holiday set in a week.", "name": "Demo Maya", "role": "Marketing lead, Demo Candle Co."}], "contactEmail": "partnerships@demo-creator.example", "manual": [{"id": "man_1", "platform": "instagram", "label": "Audience who are women", "value": "82%", "asOf": "2026-09-20"}]}', draft_saved_at = '2026-09-24T12:00:00.000Z' WHERE id = 1;
INSERT INTO media_kit_versions (version, content, slug, published_at) VALUES (1, '{"name": "Sheila Bruce", "handles": {"tiktok": "@demo.sheila", "instagram": "@demo.sheila"}, "niche": "Hosting \u00b7 tablescapes \u00b7 everyday luxury", "location": "Mobile, Alabama", "positioning": "Hosting that makes every guest feel celebrated.", "bio": "Hosting, table styling and everyday luxury for women who love to gather.", "photoKey": null, "pillars": [{"title": "Table styling", "text": "Tablescapes for every season"}, {"title": "Easy entertaining", "text": "Gatherings without the stress"}, {"title": "Holiday hosting", "text": "Menus, tables and gifts"}], "series": [{"title": "Sunday Table", "text": "A weekly 60-second table reset"}], "showcase": ["demo_clip_1", "demo_clip_2", "demo_clip_3"], "collabs": [{"id": "col_1", "brand": "Demo Candle Co.", "website": null, "logoKey": null, "what": "2 TikToks for a holiday launch", "result": "48K views, 1.2K saves", "dealId": null}, {"id": "col_2", "brand": "Demo Linens", "website": null, "logoKey": null, "what": "Instagram Reel + Stories", "result": "", "dealId": null}], "packages": [{"id": "pkg_tiktok", "name": "1 TikTok video", "items": [{"key": "tiktok_video", "qty": 1}], "startingAt": 800, "onRequest": false, "floor": 650, "target": 1000, "note": "Concept, filming and editing; posted on my TikTok.", "showOnKit": true}, {"id": "pkg_reel_story", "name": "Instagram Reel + Story set", "items": [{"key": "ig_reel", "qty": 1}, {"key": "ig_story_set", "qty": 1}], "startingAt": null, "onRequest": true, "floor": null, "target": null, "note": "A Reel plus three Story frames with your link.", "showOnKit": true}, {"id": "pkg_bundle", "name": "3-video bundle", "items": [{"key": "tiktok_video", "qty": 2}, {"key": "ig_reel", "qty": 1}], "startingAt": 2100, "onRequest": false, "floor": 1800, "target": 2400, "note": "Three videos across TikTok and Instagram over a month.", "showOnKit": true}, {"id": "pkg_ugc", "name": "Video for your channels (no post)", "items": [{"key": "ugc_video", "qty": 1}], "startingAt": 350, "onRequest": false, "floor": 250, "target": 450, "note": "A finished video for you to post.", "showOnKit": true}], "addons": {"usagePctPer30d": 30, "paidUsagePctPer30d": 40, "exclusivityPctPerMonth": 25, "rushPct": null, "bundleDiscountPct": 10, "killFeePct": 50, "upfrontPct": 50, "upfrontOver": 1000, "netDays": 30, "revisionRounds": 2}, "testimonials": [{"quote": "Sheila''s table sold out our holiday set in a week.", "name": "Demo Maya", "role": "Marketing lead, Demo Candle Co."}], "contactEmail": "partnerships@demo-creator.example", "manual": [{"id": "man_1", "platform": "instagram", "label": "Audience who are women", "value": "82%", "asOf": "2026-09-20"}]}', 'sheila', '2026-09-24T12:00:00.000Z');
INSERT INTO brands (id, name, website, program_url, socials, fit_score, fit_reasons, why_now, source_links, origin, status, kind, budget_signal, why_sourced) VALUES ('demo_brand_1', 'Maison Lumière Candles', 'https://maisonlumiere.example/', NULL, '{"instagram": "https://www.instagram.com/maisonlumiere"}', 0.96, '["Matches your \"Table styling\" theme", "Sponsors creators your size"]', 'Sponsored 3 creators in your niche this month', '["https://maisonlumiere.example/pages/creators"]', 'finder', 'saved', 'brand', '{"level":"paying","evidence":[{"text":"Paid creator program: \"we pay creators a flat fee per video\"","url":"https://maisonlumiere.example/pages/creators"}]}', '[{"text":"Launching a holiday table collection in October","url":"https://maisonlumiere.example/blogs/news/holiday-collection"}]');
INSERT INTO brand_contacts (id, brand_id, kind, value, found_on_url) VALUES ('demo_ct_1', 'demo_brand_1', 'role_email', 'partnerships@maisonlumiere.example', 'https://maisonlumiere.example/pages/contact');
INSERT INTO brands (id, name, website, program_url, socials, fit_score, fit_reasons, why_now, source_links, origin, status, kind, budget_signal, why_sourced) VALUES ('demo_brand_2', 'Golden Hour Tableware', 'https://goldenhourtable.example/', NULL, '{"instagram": "https://www.instagram.com/goldenhourtable"}', 0.9, '["Hosting and entertaining fit", "Audience overlap: women 30-55"]', 'Ran #ad posts with 2 creators from your research brief', '["https://goldenhourtable.example/pages/creators"]', 'finder', 'saved', 'brand', '{"level":"paying","evidence":[{"text":"Paid partnership tag on @demo.tablescapes Reel, 3 Sep","url":"https://www.instagram.com/p/demo-golden"}]}', '[{"text":"Their new stoneware line is shot on brunch tables like yours","url":"https://goldenhourtable.example/collections/stoneware"}]');
INSERT INTO brand_contacts (id, brand_id, kind, value, found_on_url) VALUES ('demo_ct_2', 'demo_brand_2', 'role_email', 'partnerships@goldenhourtable.example', 'https://goldenhourtable.example/pages/contact');
INSERT INTO brands (id, name, website, program_url, socials, fit_score, fit_reasons, why_now, source_links, origin, status, kind, budget_signal, why_sourced) VALUES ('demo_brand_3', 'Petal Post Florals', 'https://petalpost.example/', NULL, '{"instagram": "https://www.instagram.com/petalpost"}', 0.85, '["Floral styling appears in your top clips"]', NULL, '["https://petalpost.example/pages/creators"]', 'finder', 'saved', 'brand', '{"level":"paying","evidence":[{"text":"Paid partnership posts with 4 lifestyle creators in September","url":"https://www.instagram.com/petalpost/tagged"}]}', '[]');
INSERT INTO brand_contacts (id, brand_id, kind, value, found_on_url) VALUES ('demo_ct_3', 'demo_brand_3', 'role_email', 'partnerships@petalpost.example', 'https://petalpost.example/pages/contact');
INSERT INTO deals (id, brand_id, stage, created_at, updated_at) VALUES ('demo_deal_2', 'demo_brand_2', 'pitch', '2026-09-22T12:00:00.000Z', '2026-09-22T12:00:00.000Z');
INSERT INTO deals (id, brand_id, stage, pitched_at, created_at, updated_at) VALUES ('demo_deal_3', 'demo_brand_3', 'follow_up', '2026-09-20T12:00:00.000Z', '2026-09-19T12:00:00.000Z', '2026-09-20T12:00:00.000Z');
INSERT INTO pitches (id, brand_id, contact_id, subject, body, dm_text, followup_1, followup_2, clip_links, status) VALUES ('demo_pitch_2', 'demo_brand_2', 'demo_ct_2', 'Creator partnership idea: Golden Hour Tableware × Sheila', 'Hi Golden Hour Tableware team,

I''m Sheila, and I set a table on camera most weeks. Your stoneware is already in my Sunday brunch videos.
My audience: women 30-55 who love hosting; 12.4K followers on TikTok (about 3.1K views a video).
Two clips that show my style:
https://demo.example/media/1
https://demo.example/media/2
Media kit: http://localhost:8787/kit/sheila

Would you be open to a paid partnership this season: one video on TikTok and Instagram featuring your stoneware?

Sheila', 'Hi Golden Hour! I set tables for 12K hosting lovers on TikTok and I would love to feature your stoneware. Media kit: http://localhost:8787/kit/sheila', 'Hi again, just floating this back up. Media kit: http://localhost:8787/kit/sheila Sheila', 'Last note from me on this one. If the timing is wrong, no problem at all. Sheila', '[]', 'drafted');
INSERT INTO pitches (id, brand_id, contact_id, subject, body, dm_text, followup_1, followup_2, clip_links, status, sent_at, next_followup_at) VALUES ('demo_pitch_3', 'demo_brand_3', 'demo_ct_3', 'Creator partnership idea: Petal Post Florals × Sheila', 'Hi Petal Post Florals team,

I''m Sheila, and I set a table on camera most weeks. Your bouquets are already in my Sunday brunch videos.
My audience: women 30-55 who love hosting; 12.4K followers on TikTok (about 3.1K views a video).
Two clips that show my style:
https://demo.example/media/1
https://demo.example/media/2
Media kit: http://localhost:8787/kit/sheila

Would you be open to a paid partnership this season: one video on TikTok and Instagram featuring your bouquets?

Sheila', 'Hi Petal Post! Media kit: http://localhost:8787/kit/sheila', 'Hi again, floating this back up. Sheila', 'Last note from me. Sheila', '[]', 'sent', '2026-09-20T12:00:00.000Z', '2026-09-25T12:00:00.000Z');

INSERT INTO deal_emails (id, deal_id, scenario, subject, subject_options, body, tone, length, source, status, created_at) VALUES ('demo_email_2', 'demo_deal_2', 'cold_pitch', 'An idea for Golden Hour Tableware: table styling content', '["An idea for Golden Hour Tableware: table styling content","Golden Hour Tableware × Sheila: a video idea","For your creator team: Table styling with Golden Hour Tableware"]', 'Hi Golden Hour Tableware team,

I''m Sheila, a table styling and easy entertaining creator. I noticed your new stoneware line is shot on brunch tables like mine, so this felt like the right moment to reach out.

My idea: a 30-second Sunday brunch reset using your stoneware.

Three ways we could do it:
Full: 2 × TikTok video + Instagram Reel, with 90 days of usage on your channels, $3,360
Standard: TikTok video, $800
Entry: Video for their channels (no post from you), $350

My media kit, with my numbers, past work and rates: http://localhost:8787/kit/sheila

Would one of these work for this season? If you have a brief or a budget in mind, I''ll shape it to fit.

Warmly,
Sheila', 'warm', 'standard', 'starter', 'draft', '2026-09-22T12:05:00.000Z');
